# Generated by Django 5.1.3 on 2025-03-10 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='wishlist',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
