# Generated by Django 5.0.7 on 2025-02-27 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('Fashion', 'Fashion'), ('Beauty', 'Beauty'), ('Accessories', 'Accessories')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Beauty',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('Fashion', 'Fashion'), ('Beauty', 'Beauty'), ('Accessories', 'Accessories')], max_length=20)),
                ('makeup_type', models.CharField(choices=[('Air Cushion', 'Air Cushion'), ('Water Cushion', 'Water Cushion'), ('Cream Cushion', 'Cream Cushion')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='makeup',
        ),
        migrations.RemoveField(
            model_name='fashion',
            name='available_colors',
        ),
        migrations.AddField(
            model_name='fashion',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Black', 'Black'), ('White', 'White'), ('Yellow', 'Yellow')], default='Red', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fashion',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Beauty', 'Beauty'), ('Accessories', 'Accessories')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fashion',
            name='fashion_type',
            field=models.CharField(choices=[('Short Sleeve', 'Short Sleeve'), ('Short Crop', 'Short Crop'), ('Long Sleeve', 'Long Sleeve'), ('Pants', 'Pants'), ('Skirt', 'Skirt'), ('Shorts', 'Shorts'), ('Cardigan', 'Cardigan'), ('Jacket', 'Jacket'), ('Sweaters', 'Sweaters'), ('Hoodie', 'Hoodie')], max_length=15),
        ),
        migrations.AlterField(
            model_name='fashion',
            name='sub_category',
            field=models.CharField(choices=[('Dress', 'Dress'), ('Shirt', 'Shirt'), ('Outerwear', 'Outerwear'), ('Bottom', 'Bottom')], max_length=20),
        ),
        migrations.AddField(
            model_name='productimage',
            name='accessories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='WebPage.accessories'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='beauty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='WebPage.beauty'),
        ),
        migrations.DeleteModel(
            name='Make_Up',
        ),
    ]
