# Generated by Django 5.1.5 on 2025-02-28 03:35

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0002_accessories_beauty_remove_productimage_makeup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='category',
        ),
        migrations.RemoveField(
            model_name='beauty',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fashion',
            name='category',
        ),
        migrations.AlterField(
            model_name='beauty',
            name='makeup_type',
            field=models.CharField(choices=[('Face', 'Face'), ('Eye', 'Eye'), ('Lips', 'Lips')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fashion',
            name='color',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Black', 'Black'), ('White', 'White'), ('Yellow', 'Yellow')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fashion',
            name='fashion_type',
            field=models.CharField(choices=[('Pants', 'Pants'), ('Skirt', 'Skirt'), ('Shorts', 'Shorts'), ('Cardigan', 'Cardigan'), ('Jacket', 'Jacket'), ('Sweaters', 'Sweaters'), ('Hoodie', 'Hoodie'), ('Short Sleeve', 'Short Sleeve'), ('Short Crop', 'Short Crop'), ('Long Sleeve', 'Long Sleeve')], max_length=15),
        ),
        migrations.AlterField(
            model_name='fashion',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=50),
        ),
    ]
