# Generated by Django 5.1.5 on 2025-02-28 07:13

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0003_remove_accessories_category_remove_beauty_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashion',
            name='color',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('White', 'White'), ('Grey', 'Grey'), ('Black', 'Black'), ('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Blue', 'Blue'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Beige', 'Beige'), ('Brown', 'Brown')], max_length=100),
        ),
    ]
