# Generated by Django 5.1.5 on 2025-03-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0003_product_category_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('beauty', 'Beauty'), ('trending', 'Trending')], default='fashion ', max_length=50),
        ),
    ]
