# Generated by Django 5.1.5 on 2025-03-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0005_alter_fashion_fashion_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='fashion',
            name='fashion_type',
            field=models.CharField(choices=[('Pants', 'Pants'), ('Skirt', 'Skirt'), ('Shorts', 'Shorts'), ('Cardigan', 'Cardigan'), ('Jacket', 'Jacket'), ('Sweaters', 'Sweaters'), ('Hoodie', 'Hoodie'), ('Short Sleeve', 'Short Sleeve'), ('Short Crop', 'Short Crop'), ('Long Sleeve', 'Long Sleeve')], max_length=15),
        ),
    ]
