# Generated by Django 5.1.5 on 2025-03-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0006_product_alter_fashion_fashion_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashion',
            name='fashion_type',
            field=models.CharField(blank=True, choices=[('Pants', 'Pants'), ('Skirt', 'Skirt'), ('Shorts', 'Shorts'), ('Cardigan', 'Cardigan'), ('Jacket', 'Jacket'), ('Sweaters', 'Sweaters'), ('Hoodie', 'Hoodie'), ('Short Sleeve', 'Short Sleeve'), ('Short Crop', 'Short Crop'), ('Long Sleeve', 'Long Sleeve')], max_length=15, null=True),
        ),
    ]
