# Generated by Django 5.1.3 on 2025-03-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0006_cart_cartitem'),
        ('WebPage', '0007_alter_fashion_fashion_type'),
    ]

    operations = [
    ]
